// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/calc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int64                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int64                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationReq) Reset() {
	*x = CalculationReq{}
	mi := &file_proto_calc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationReq) ProtoMessage() {}

func (x *CalculationReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationReq.ProtoReflect.Descriptor instead.
func (*CalculationReq) Descriptor() ([]byte, []int) {
	return file_proto_calc_proto_rawDescGZIP(), []int{0}
}

func (x *CalculationReq) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *CalculationReq) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type CalculationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           int64                  `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationRes) Reset() {
	*x = CalculationRes{}
	mi := &file_proto_calc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationRes) ProtoMessage() {}

func (x *CalculationRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationRes.ProtoReflect.Descriptor instead.
func (*CalculationRes) Descriptor() ([]byte, []int) {
	return file_proto_calc_proto_rawDescGZIP(), []int{1}
}

func (x *CalculationRes) GetRes() int64 {
	if x != nil {
		return x.Res
	}
	return 0
}

var File_proto_calc_proto protoreflect.FileDescriptor

const file_proto_calc_proto_rawDesc = "" +
	"\n" +
	"\x10proto/calc.proto\x12\x04calc\",\n" +
	"\x0eCalculationReq\x12\f\n" +
	"\x01a\x18\x01 \x01(\x03R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x03R\x01b\"\"\n" +
	"\x0eCalculationRes\x12\x10\n" +
	"\x03res\x18\x01 \x01(\x03R\x03res2?\n" +
	"\n" +
	"Calculator\x121\n" +
	"\x03Add\x12\x14.calc.CalculationReq\x1a\x14.calc.CalculationResB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_calc_proto_rawDescOnce sync.Once
	file_proto_calc_proto_rawDescData []byte
)

func file_proto_calc_proto_rawDescGZIP() []byte {
	file_proto_calc_proto_rawDescOnce.Do(func() {
		file_proto_calc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calc_proto_rawDesc), len(file_proto_calc_proto_rawDesc)))
	})
	return file_proto_calc_proto_rawDescData
}

var file_proto_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_calc_proto_goTypes = []any{
	(*CalculationReq)(nil), // 0: calc.CalculationReq
	(*CalculationRes)(nil), // 1: calc.CalculationRes
}
var file_proto_calc_proto_depIdxs = []int32{
	0, // 0: calc.Calculator.Add:input_type -> calc.CalculationReq
	1, // 1: calc.Calculator.Add:output_type -> calc.CalculationRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_calc_proto_init() }
func file_proto_calc_proto_init() {
	if File_proto_calc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calc_proto_rawDesc), len(file_proto_calc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calc_proto_goTypes,
		DependencyIndexes: file_proto_calc_proto_depIdxs,
		MessageInfos:      file_proto_calc_proto_msgTypes,
	}.Build()
	File_proto_calc_proto = out.File
	file_proto_calc_proto_goTypes = nil
	file_proto_calc_proto_depIdxs = nil
}
